name: Sync from Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # setiap hari jam 06:00 WITA

jobs:
  selective-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo (this repo)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch upstream and checkout upstream/main to temp dir
        run: |
          git clone --depth=1 --branch=main https://github.com/nikkinikki-org/OpenWrt-nikki.git upstream-source

      - name: Compare and Sync changed files only (non-destructive)
        run: |
          mkdir -p tmp-sync
          rsync -av --delete --exclude='.git/' --exclude='*mihomo*' upstream-source/luci-app-nikki/ ./luci-app-nikki/
          rsync -av --delete --exclude='.git/' --exclude='*mihomo*' upstream-source/nikki/ ./nikki/

      - name: Commit if there are changes
        id: commit_check
        run: |
          git add luci-app-nikki nikki || true
          if ! git diff --cached --quiet; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            git commit -m "Sync luci-app-nikki and nikki from upstream (non-overwrite)"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_WORKFLOW }}@github.com/${{ github.repository }}.git
            git push origin main
          else
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Notify to Telegram if files changed
        if: steps.commit_check.outputs.changes_detected == 'true'
        run: |
          REPO_URL="https://github.com/rivandraa/openwrt-nikki-tproxy"  # ganti sesuai repo kamu
          BRANCH="main"
      
          FILES=$(git diff --name-status HEAD^ HEAD | grep -E '^(A|M|D)\s+(luci-app-nikki|nikki)/' || true)
      
          if [ -n "$FILES" ]; then
            CHANGED=$(echo "$FILES" | while read status path; do
              ICON=""
              case "$status" in
                A) ICON="🆕" ;;
                M) ICON="✏️" ;;
                D) ICON="❌" ;;
                *) ICON="📄" ;;
              esac
      
              ESCAPED_NAME=$(echo "$path" | sed -e 's/\*/\\*/g' \
                                                -e 's/\[/\\[/g' \
                                                -e 's/\]/\\]/g' \
                                                -e 's/(/\\(/g' \
                                                -e 's/)/\\)/g')
      
              if [ "$status" = "D" ]; then
                echo "- $ICON $ESCAPED_NAME"
              else
                echo "- $ICON [$ESCAPED_NAME]($REPO_URL/blob/$BRANCH/$path)"
              fi
            done)
      
            MSG=$(printf "🛎️ *Sync dari upstream selesai*\n\n*File berubah:*\n%s" "$CHANGED")
          else
            MSG=$(printf "🛎️ *Sync dari upstream selesai*\n\nTidak ada file yang berubah di folder target.")
          fi
      
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$MSG" \
            -d parse_mode="Markdown"
