include $(TOPDIR)/rules.mk

PKG_VERSION:=v1.23.2-Mod
PKG_RELEASE:=1

LUCI_TITLE:=LuCI Support for Nikki TProxy
LUCI_DEPENDS:=+luci-base +nikki

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
