name: telegram test upload

on:
  workflow_dispatch:

jobs:
  telegram-test:
    runs-on: ubuntu-latest
    steps:
      - name: Buat dummy file zip
        run: |
          echo "dummy content" > dummy.txt
          zip Nikki_TProxy_v1.24.2-Mod-r1_Nikki_v1.19.13-Mod-r2_aarch64_generic.zip dummy.txt

      - name: Upload dummy ZIP ke Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -e
          ORIGINAL_FILE="Nikki_TProxy_v1.24.2-Mod-r1_Nikki_v1.19.13-Mod-r2_aarch64_generic.zip"

          echo "📦 Asli: $ORIGINAL_FILE"

          CAPTION="🧪 <b>Testing Upload</b>
          
          File: <code>$ORIGINAL_FILE</code>"

          # Tentukan nama file aman untuk Telegram
          FILENAME="$(basename "$ORIGINAL_FILE")"
          MAX_LEN=63
          if [ ${#FILENAME} -gt $MAX_LEN ]; then
            EXT="${FILENAME##*.}"
            NAME="${FILENAME%.*}"
            SAFE_NAME="${NAME:0:$MAX_LEN}.${EXT}"
          else
            SAFE_NAME="$FILENAME"
          fi

          echo "📂 Filename dikirim: $SAFE_NAME"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
            -F chat_id="${TELEGRAM_CHAT_ID}" \
            -F "document=@${ORIGINAL_FILE};filename=${SAFE_NAME}" \
            -F caption="$CAPTION" \
            -F parse_mode="HTML"

