name: Sync from Upstream 12 jam-modif

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # 06:00 WITA
    - cron: '0 10 * * *'  # 18:00 WITA

jobs:
  selective-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo (this repo)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/nikkinikki-org/OpenWrt-nikki.git
          git fetch upstream main

      - name: Get previous synced commit
        id: get_last_commit
        run: |
          if [ -f .last-upstream-commit ]; then
            LAST_COMMIT=$(cat .last-upstream-commit)
          else
            LAST_COMMIT=$(git rev-parse upstream/main~1)
          fi
          echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT

      - name: Get latest upstream commit
        id: get_latest_commit
        run: |
          LATEST=$(git rev-parse upstream/main)
          echo "latest_commit=$LATEST" >> $GITHUB_OUTPUT

      - name: Clone upstream repo for file comparison
        run: |
          git clone --depth=1 --no-recurse-submodules --branch=main https://github.com/nikkinikki-org/OpenWrt-nikki.git upstream-source

      - name: List real changed files from upstream only
        id: changed_files
        run: |
          mkdir -p .git/tmp-base
          > changed_files.txt

          for file in $(git diff --name-only ${{ steps.get_last_commit.outputs.last_commit }} ${{ steps.get_latest_commit.outputs.latest_commit }} | grep -E '^(luci-app-nikki|nikki)/'); do
            BASE=".git/tmp-base/$file"
            REMOTE="upstream-source/$file"

            mkdir -p "$(dirname "$BASE")"
            git show "${{ steps.get_last_commit.outputs.last_commit }}:$file" > "$BASE" 2>/dev/null || touch "$BASE"

            if [ -f "$REMOTE" ]; then
              if ! cmp -s "$REMOTE" "$BASE"; then
                echo "$file" >> changed_files.txt
              fi
            fi
          done

          cat changed_files.txt
          echo "changed=$(paste -sd ',' changed_files.txt)" >> $GITHUB_OUTPUT

      - name: Merge and update files
        run: |
          for file in $(cat changed_files.txt); do
            echo "🔄 Merging file: $file"
            LOCAL="$file"
            REMOTE="upstream-source/$file"
            BASE=".git/tmp-base/$file"

            mkdir -p "$(dirname "$LOCAL")"

            if [ -f "$REMOTE" ]; then
              if [ -f "$LOCAL" ]; then
                git merge-file -p -L LOCAL -L BASE -L UPSTREAM "$LOCAL" "$BASE" "$REMOTE" > "$LOCAL.merged" || true

                if [ -s "$LOCAL.merged" ]; then
                  if ! cmp -s "$LOCAL.merged" "$LOCAL"; then
                    mv "$LOCAL.merged" "$LOCAL"
                    echo "✅ Merge sukses: $file"
                  else
                    echo "ℹ️ Tidak ada perubahan isi: $file"
                    rm -f "$LOCAL.merged"
                  fi
                else
                  echo "⚠️ Merge kosong: $file"
                  rm -f "$LOCAL.merged"
                fi
              else
                cp -a "$REMOTE" "$LOCAL"
                echo "📥 Ambil file baru: $file"
              fi
            else
              echo "⚠️ File remote tidak ditemukan: $REMOTE"
            fi
          done

      - name: Update .last-upstream-commit
        run: |
          echo "${{ steps.get_latest_commit.outputs.latest_commit }}" > .last-upstream-commit

      - name: Commit if there are changes
        id: commit_check
        run: |
          git add -A

          if ! git diff --cached --quiet; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            git commit -m "Sync from upstream: ${{ steps.get_latest_commit.outputs.latest_commit }}"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_WORKFLOW }}@github.com/${{ github.repository }}.git
            git push origin main
          else
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Notify to Telegram
        if: always()
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          BRANCH="main"
          FILES=$(git diff-tree --no-commit-id --name-status -r HEAD | grep -E '^(A|M|D)\s+(luci-app-nikki|nikki)/' || true)

          if [ -n "$FILES" ]; then
            CHANGED=$(echo "$FILES" | while read status path; do
              case "$status" in
                A) ICON="🆕" ;;
                M) ICON="✏️" ;;
                D) ICON="❌" ;;
                *) ICON="📄" ;;
              esac

              ESCAPED_NAME=$(echo "$path" | sed -e 's/([][*()])/\\&/g')

              if grep -q '<<<<<<< LOCAL' "$path" 2>/dev/null; then
                CONFLICT_NOTE=" ⚠️ *File Konflik*"
              else
                CONFLICT_NOTE=""
              fi

              if [ "$status" = "D" ]; then
                echo "- $ICON $ESCAPED_NAME$CONFLICT_NOTE"
              else
                echo "- $ICON [$ESCAPED_NAME]($REPO_URL/blob/$BRANCH/$path)$CONFLICT_NOTE"
              fi
            done)
            MSG=$(printf "🛎️ *Sync dari upstream selesai*\n\n*File berubah:*\n%s" "$CHANGED")
          else
            MSG=$(printf "🛎️ *Sync dari upstream selesai*\n\nTidak ada Update.")
          fi

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$MSG" \
            -d parse_mode="Markdown"
