name: Sync from Upstream (by commit)

on:
  workflow_dispatch:

jobs:
  selective-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo (this repo)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/nikkinikki-org/OpenWrt-nikki.git
          git fetch upstream main

      - name: Get previous synced commit
        id: get_last_commit
        run: |
          if [ -f .last-upstream-commit ]; then
            LAST_COMMIT=$(cat .last-upstream-commit)
          else
            # Default to 1 commit before upstream/main if not found
            LAST_COMMIT=$(git rev-parse upstream/main~1)
          fi
          echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT

      - name: Get latest upstream commit
        id: get_latest_commit
        run: |
          LATEST=$(git rev-parse upstream/main)
          echo "latest_commit=$LATEST" >> $GITHUB_OUTPUT

      - name: List changed files from upstream
        id: changed_files
        run: |
          git diff --name-only ${{ steps.get_last_commit.outputs.last_commit }} ${{ steps.get_latest_commit.outputs.latest_commit }} \
            | grep -E '^(luci-app-nikki|nikki)/' > changed_files.txt || true
          cat changed_files.txt
          echo "changed=$(paste -sd ',' changed_files.txt)" >> $GITHUB_OUTPUT

      - name: Clone upstream repo for file copy
        run: |
          git clone --depth=1 --branch=main https://github.com/nikkinikki-org/OpenWrt-nikki.git upstream-source

      - name: Copy only changed files
        run: |
          while IFS= read -r file; do
            echo "Syncing: $file"
            mkdir -p "$(dirname "$file")"
            cp -a "upstream-source/$file" "$file" || true
          done < changed_files.txt

      - name: Update .last-upstream-commit
        run: |
          echo "${{ steps.get_latest_commit.outputs.latest_commit }}" > .last-upstream-commit

      - name: Commit if there are changes
        id: commit_check
        run: |
          git add .last-upstream-commit luci-app-nikki nikki || true
          if ! git diff --cached --quiet; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            git commit -m "Sync from upstream: ${{ steps.get_latest_commit.outputs.latest_commit }}"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_WORKFLOW }}@github.com/${{ github.repository }}.git
            git push origin main
          else
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Notify to Telegram
        if: steps.commit_check.outputs.changes_detected == 'true'
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          BRANCH="main"
          FILES=$(git diff --name-status HEAD^ HEAD | grep -E '^(A|M|D)\s+(luci-app-nikki|nikki)/' || true)

          if [ -n "$FILES" ]; then
            CHANGED=$(echo "$FILES" | while read status path; do
              case "$status" in
                A) ICON="🆕" ;;
                M) ICON="✏️" ;;
                D) ICON="❌" ;;
                *) ICON="📄" ;;
              esac

              ESCAPED_NAME=$(echo "$path" | sed -e 's/([][*()])/\\&/g')

              if [ "$status" = "D" ]; then
                echo "- $ICON $ESCAPED_NAME"
              else
                echo "- $ICON [$ESCAPED_NAME]($REPO_URL/blob/$BRANCH/$path)"
              fi
            done)
            MSG=$(printf "🛎️ *Sync dari upstream selesai*\n\n*File berubah:*\n%s" "$CHANGED")
          else
            MSG="🛎️ *Sync dari upstream selesai*\n\n*Tidak ada file yang berubah di folder target.*"
          fi

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$MSG" \
            -d parse_mode="Markdown"
